import { AppSidebar } from "@/components/app-sidebar";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body className="w-full font-pretendard antialiased">
        <SidebarProvider>
          <AppSidebar />
          <SidebarTrigger />
          <main className="w-full flex flex-col p-12 gap-12">{children}</main>
        </SidebarProvider>
      </body>
    </html>
  );
}
